window.onload = function () {     
    var _news21footer = document.getElementById('news21-footer');     

    if(_news21footer != null) {         
        document.getElementById('news21-footer').innerHTML = '<div id="news21-footer-top"></div><div id="news21-footer-content"></div><div class="clear"></div><div id="news21-footer-copy">Copyright News21.com 2006-2010. All rights reserved.</div>';     

        document.getElementById('news21-footer-content').innerHTML = '<div id="news21-footer-projects" ><h3>2009 Projects</h3><ul class="news21-clean"> <li class="news21-footer-li"><a class="news21-footer-a" href="http://asu.news21.com/">The Latino Experience</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://berkeley.news21.com/">Intersections</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">Charter School Explosion</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://umd.news21.com/">The New Voters</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://unc.news21.com/">Powering a Nation</a></li>  <li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">Young Urban Adults</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://usc.news21.com/">Southwestern Shifts</a></li>  <li class="news21-footer-li"><a class="news21-footer-a" href="http://syracuse.news21.com">The Young &amp; the Wireless</a></li> </ul> </div>' +          

'<div id="news21-footer-newsrooms" ><h3>Newsrooms</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://asu.news21.com/">Arizona State</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://berkeley.news21.com/">Berkeley</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">Columbia</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://umd.news21.com">Maryland</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://unc.news21.com/">North Carolina</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">Northwestern</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://usc.news21.com/">Southern California</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://syracuse.news21.com/">Syracuse</a></li></ul> </div>' +          

'<div id="news21-footer-category" ><h3>Topics</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/cities">Cities</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/culture">Culture</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/demographics">Demographics</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/economics">Economics</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/education">Education</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/employment">Employment</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/environment">Environment</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/ethnicity">Ethnicity</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/gender">Gender</a></li> </ul> </div>' +          

'<div id="news21-footer-category2" ><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/immigration">Immigration</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/innovation">Innovation</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/policy">Policy</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/politics">Politics</a></li><li class="news21-footer-li"><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/spirituality">Spirituality</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/technology">Technology</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/urbanissues">Urban Issues</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/topics/youth">Youth</a></li> </ul> </div>'+          

'<div id="news21-footer-years" ><h3>Archives</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com">Changing America &middot; 2009</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://newsinitiative.org/projects">What&#146;s at Stake: Election &middot; 2008</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://newsinitiative.org/projects">Faces of Faith in America &middot; 2007</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://newsinitiative.org/projects">Liberty vs. Security &middot; 2006</a></li> </ul> <h3>News21 In Depth</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://initiative.news21.com">The Initiative</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/initiative">Carnegie-Knight Initiative</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/participants">Participants</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/news21-in-the-news/">New21 in the News</a></li> </ul> </div>' +          

'<div id="news21-footer-social" ><h3>Social</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://innovate.news21.com/">Innovation Blog</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://tools.news21.com/">J-Tools Blog</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://twitter.com/news21">Twitter</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://www.facebook.com/news21">Facebook</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://www.youtube.com/news21">YouTube</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://www.linkedin.com/companies/news21?trk=co_search_results&goback=.cps_1267035910714_1">LinkedIn</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://vimeo.com/channels/news21">Vimeo</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://www.flickr.com/groups/news21/">Flickr</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://delicious.com/search?p=News21&chk=&context=main|&fr=del_icio_us&lc=/">Del.icio.us</a></li></ul> </div>' +          

'<div id="news21-footer-multimedia" ><h3>Other</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/download/">Free Content</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/widgets/">Widgets</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://labs.news21.com/">iPhone App</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://labs.news21.com">Android App</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://labs.news21.com/">Open Source</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/about/incubator-best-practices/">Recreating News21</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com/innovation-roundup//">Innovation Lessons</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://innovate.news21.com/?tag=compare">Compare Projects</a></li></ul> </div>';
    } 
    
    var _news21header = document.getElementById('news21-header');     
    var _searchAffiliates = {'arizonastate':'Arizona State','berkeley':'Berkeley','columbia':'Columbia','maryland':'Maryland','northcarolina':'North Carolina','northwestern':'Northwestern','southerncalifornia':'Southern California','syracuse':'Syracuse'};
    
    if(_news21header != null) {    
        document.getElementById('news21-header').innerHTML = '<form method="get" action="http://news21.com/search/" id="news21-search" class="news21-search" name="news21-search"><input type="hidden" value="" name="affiliate" id="news21-search-affiliate"/><input class="clearInput" type="text" name="q" value="Search ..."  onblur="if (this.value == \'\') this.value = \'Search ...\';" onfocus="if (this.value == \'Search ...\') this.value = \'\';" /></form>';
        if(_news21header.className != "") document.getElementById('news21-search-affiliate').value=_searchAffiliates[_news21header.className];
    }
    
}