window.onload = function () {
    var _news21footer = document.getElementById('news21-footer');
    if(_news21footer != null) {
        document.getElementById('news21-footer').innerHTML = '<div id="news21-footer-top"></div><div id="news21-footer-content"></div><div class="clear"></div><div id="news21-footer-copy">Copyright News21.com 2006-2010. All rights reserved.</div>';

        document.getElementById('news21-footer-content').innerHTML = '<div id="news21-footer-projects" ><h3>2009 Projects</h3><ul class="news21-clean"> <li class="news21-footer-li"><a class="news21-footer-a" href="http://asu.news21.com/">The Latino Experience</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://berkeley.news21.com/">Intersections</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">Charter School Explosion</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://umd.news21.com/">The New Voters</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://unc.news21.com/">Powering a Nation</a></li>  <li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">Young Urban Adults</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://usc.news21.com/">Southwestern Shifts</a></li>  <li class="news21-footer-li"><a class="news21-footer-a" href="http://syracuse.news21.com">The Young &amp; the Wireless</a></li> </ul> </div>' +

        '<div id="news21-footer-newsrooms" ><h3>Newsrooms</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://asu.news21.com/">Arizona State</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://berkeley.news21.com/">Berkeley</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">Columbia</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://umd.news21.com">Maryland</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://unc.news21.com/">North Carolina</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">Northwestern</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://usc.news21.com/">Southern California</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://syracuse.news21.com/">Syracuse</a></li></ul> </div>' +

        '<div id="news21-footer-category" ><h3>Topics</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/immigration">Immigration</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/cities">Cities</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/culture">Culture</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/demographics">Demographics</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/economics">Economics</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/education">Education</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/employment">Employment</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/environment">Environment</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/ethnicity">Ethnicity</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/gender">Gender</a></li> </ul> </div>' +

        '<div id="news21-footer-category2" ><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/innovation">Innovation</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/neighborhoods">Neighborhoods</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/policy">Policy</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/politics">Politics</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/poverty">Poverty</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/regions">Regions</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/spirituality">Spirituality</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/technology">Technology</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/urbanissues">Urban Issues</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://beta.news21.com/topics/youth">Youth</a></li> </ul> </div>'+

        '<div id="news21-footer-years" ><h3>Archives</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://news21.com">Changing America &middot; 2009</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://newsinitiative.org/projects">What&#146;s at Stake: Election &middot; 2008</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://newsinitiative.org/projects">Faces of Faith in America &middot; 2007</a></li> <li class="news21-footer-li"><a class="news21-footer-a" href="http://newsinitiative.org/projects">Liberty vs. Security &middot; 2006</a></li> </ul> </div>' +

        '<div id="news21-footer-social" ><h3>Social</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://unc.news21.com/">Innovation Blog</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">J-Tools Blog</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://asu.news21.com/">Twitter</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://berkeley.news21.com/">Facebook</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">YouTube</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://umd.news21.com">LinkedIn</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://unc.news21.com/">Vimeo</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">Flickr</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://northwestern.news21.com/">Del.icio.us</a></li></ul> </div>' +

        '<div id="news21-footer-multimedia" ><h3>Other</h3><ul class="news21-clean"><li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">Free Content</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://asu.news21.com/">Widgets</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://columbia.news21.com/">iPhone App</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://umd.news21.com">Android App</a></li><li class="news21-footer-li"><a class="news21-footer-a" href="http://berkeley.news21.com/">Open Source</a></li></ul> </div>';
    }
}